version: '2'
services:
  jhbodyprojectadmin-app:
    image: jhbodyprojectadmin
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhbodyprojectadmin-postgresql:5432/jhBodyProjectAdmin
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 5001:5001
  jhbodyprojectadmin-postgresql:
    extends:
      file: postgresql.yml
      service: jhbodyprojectadmin-postgresql
